export const PADDLE_WIDTH_RATIO = 0.32;
export const PADDLE_HEIGHT_RATIO = 0.042;
export const PADDLE_EDGE_GAP = 24;
export const PADDLE_MAX_BOUNCE_ANGLE = Math.PI / 3;
export const PADDLE_VELOCITY_INFLUENCE = 0.18;
export const PADDLE_VELOCITY_HALF_LIFE_SECONDS = 0.1;
export const PADDLE_VELOCITY_EPSILON = 0.01;
export const PADDLE_INPUT_SEND_RATE = 30;
export const REMOTE_PADDLE_INTERPOLATION_HALF_LIFE_SECONDS = 0.035;
export const REMOTE_PADDLE_INTERPOLATION_EPSILON = 0.0005;
export const NETWORK_PING_INTERVAL_MS = 1_000;
export const NETWORK_LATENCY_SMOOTHING_FACTOR = 0.2;
export const GAME_SNAPSHOT_SEND_RATE = 20;
export const REPLICA_INTERPOLATION_HALF_LIFE_SECONDS = 0.04;
export const REPLICA_INTERPOLATION_EPSILON = 0.0005;

export const BALL_RADIUS_RATIO = 0.035;
export const BALL_SERVE_VELOCITY_X = 0.32;
export const BALL_SERVE_VELOCITY_Y = 0.42;
export const BALL_SPEED_UP_PER_PADDLE_HIT = 1.07;
export const BALL_IMPACT_REFERENCE_SPEED = 1.5;

export const GAME_TICK_RATE = 120;
export const PADDLE_INPUT_SEND_INTERVAL_TICKS = Math.max(
  1,
  Math.round(GAME_TICK_RATE / PADDLE_INPUT_SEND_RATE),
);
export const GAME_SNAPSHOT_SEND_INTERVAL_TICKS = Math.max(
  1,
  Math.round(GAME_TICK_RATE / GAME_SNAPSHOT_SEND_RATE),
);
export const MAX_FRAME_TIME_SECONDS = 0.1;
export const MATCH_WINNING_SCORE = 5;
export const MATCH_POINT_PAUSE_TICKS = Math.round(GAME_TICK_RATE * 0.65);
export const MATCH_OPENING_COUNTDOWN_FROM = 3;
export const MATCH_OPENING_COUNTDOWN_STEP_TICKS = Math.round(
  GAME_TICK_RATE * 0.6,
);
export const MATCH_POINT_COUNTDOWN_FROM = 2;
export const MATCH_POINT_COUNTDOWN_STEP_TICKS = Math.round(
  GAME_TICK_RATE * 0.5,
);
